service: dynamodbcrudtest

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessLocalUser
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:*
      Resource: '*'

custom:
  tableName: dynamoCrudTest

functions:
  getUser:
    handler: src/lambdas/get-user.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
  createUser:
    handler: src/lambdas/create-user.handler
    events:
      - http:
          path: create-user
          method: POST
          cors: true
  updateUser:
    handler: src/lambdas/update-user.handler
    events:
      - http:
          path: update-user/{ID}
          method: PUT
          cors: true

resources:
  Resources:
    DynamoCrudTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST